Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/test/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
N = 100
net = op.network.Cubic(shape=[N, N, 1], spacing=2.5e-5)
geom = op.geometry.SpheresAndCylinders(network=net, pores=net.Ps, throats=net.Ts)
water = op.phases.Water(network=net)
phys = op.physics.Standard(network=net, phase=water, geometry=geom)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn [2], line 3[0m
[1;32m      1[0m N [38;5;241m=[39m [38;5;241m100[39m
[1;32m      2[0m net [38;5;241m=[39m op[38;5;241m.[39mnetwork[38;5;241m.[39mCubic(shape[38;5;241m=[39m[N, N, [38;5;241m1[39m], spacing[38;5;241m=[39m[38;5;241m2.5e-5[39m)
[0;32m----> 3[0m geom [38;5;241m=[39m [43mop[49m[38;5;241;43m.[39;49m[43mgeometry[49m[38;5;241m.[39mSpheresAndCylinders(network[38;5;241m=[39mnet, pores[38;5;241m=[39mnet[38;5;241m.[39mPs, throats[38;5;241m=[39mnet[38;5;241m.[39mTs)
[1;32m      4[0m water [38;5;241m=[39m op[38;5;241m.[39mphases[38;5;241m.[39mWater(network[38;5;241m=[39mnet)
[1;32m      5[0m phys [38;5;241m=[39m op[38;5;241m.[39mphysics[38;5;241m.[39mStandard(network[38;5;241m=[39mnet, phase[38;5;241m=[39mwater, geometry[38;5;241m=[39mgeom)

[0;31mAttributeError[0m: module 'openpnm' has no attribute 'geometry'
AttributeError: module 'openpnm' has no attribute 'geometry'

